AllCops:
  Exclude:
    - vendor/**
    - bin/**

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

ClassLength:
  Enabled: false

Documentation:
  # don't require classes to be documented
  Enabled: false

Encoding:
  # no need to always specify encoding
  Enabled: false

FileName:
  # allow ruby-enum.rb
  Enabled: false

RaiseArgs:
  Enabled: false
